# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodations', to='events.Event'),
        ),
    ]
