# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160816_1836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accomodation',
            unique_together=set([('event', 'location', 'start_date', 'end_date', 'price_per_night')]),
        ),
    ]
