# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160519_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='signup_end_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='signup_end_time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
