# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='email',
        ),
    ]
