# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0002_auto_20160517_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'trainer'), (1, 'child'), (2, 'parent')], verbose_name='typ užívateľa'),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='TrainerProfile',
        ),
        migrations.AddField(
            model_name='parentchildren',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='user_profiles.ChildProfile', verbose_name='deti'),
        ),
        migrations.AddField(
            model_name='parentchildren',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
