# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_auto_20160518_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='member_since',
            field=models.DateField(verbose_name='vstup do klubu'),
        ),
    ]
