# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20160518_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentchildren',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', to='user_profiles.ChildProfile', verbose_name='deti'),
        ),
    ]
