# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_auto_20160518_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='childprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
